app/urls.py
from django.urls import path
from .views import home, call_patient

app_name = 'app'

urlpatterns = [
    path('', home, name='home'),
    path('call/<int:res_id>/', call_patient, name='call_patient'),
]

hospitalia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('account.urls')),
    path('', include('app.urls')),
]

templates/app/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}Home page{% endblock title %}
{% block content %}
    {% if usertype == 'doctor' %}

    <main class="bg-[#1B2631] w-full md:w-[calc(100%-256px)] mx-auto">
      <!-- Content -->
        <div class="p-6">
            {% if messages %}
            <div class='max-w-md w-full bg-green-700/70 mx-auto shadow-lg rounded-lg px-6 py-5 h-36 mb-8 mt-6 text-white text-lg font-medium'>
                <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
                </ul>
            </div>
            {% endif %}
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
                <div class="bg-gray-900 rounded-md border border-gray-700 p-6 shadow-md shadow-black/5">
                    <div class="flex items-center gap-4 mb-6">
                        <img class='rounded-full bg-green-700/80 p-1 w-14 h-14' src='{% static "img/patientt.svg" %}' />
                        <div>
                            <div class="flex items-center mb-1">
                                <div class="text-2xl font-semibold text-gray-50">{{first.patient.full_name}}</div>
                            </div>
                            <div class="text-md font-medium text-gray-300">Current Patient</div>
                        </div>
                    </div>

                    {% if first %}
                        <form class='flex flex-row items-end justify-between' method='post' action='{% url "app:call_patient" first.id %}'>
                            {% csrf_token %}
                            <div class='max-w-lg w-1/2'>
                                <label class='text-sm text-gray-300 font-medium'>Select a Room: </label>
                                <select name="room" id="select" class="block w-full rounded-md border border-slate-300 bg-white px-3 py-4 font-semibold text-gray-600 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-1 focus:ring-sky-500 text-sm lg:text-md">
                                    {% for room in  rooms %}
                                        <option class="font-semibold text-slate-300">{{room.number}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <button type='submit' class="text-white bg-green-700/70 font-medium text-lg px-4 py-2 rounded-md transition duration-300 ease-in-out hover:bg-green-700">CALL</button>
                        </form>
                    {% else %}
                        <span class='text-gray-200 text-md font-medium'>You don't have any patients now.</span>
                    {% endif %}
                </div>
                <div class="bg-gray-900 rounded-md border border-gray-700 p-6 shadow-md shadow-black/5">
                    <div class="flex justify-between mb-4">
                        <div>
                            <div class="flex items-center mb-1">
                                <div class="text-2xl font-semibold text-gray-50">{{count}}</div>
                            </div>
                            <div class="text-md font-medium text-gray-200">Patients Left</div>
                        </div>
                    </div>
                </div>
                <div class="bg-gray-900 rounded-md border border-gray-700 p-6 shadow-md shadow-black/5">
                    <div class="flex items-center gap-4 mb-6">
                        <div>
                            <div class="flex items-center mb-1 text-gray-50">
                                <div class="text-2xl font-semibold">
                                    {% if first %}
                                        {{first.reservation_date|date:'Y-m-d H:i'}}
                                    {% else %}
                                        0
                                    {% endif %}
                                </div>
                            </div>
                            <div class="text-md font-medium text-gray-200">Visit Time</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      <!-- End Content -->
    </main>
    {% else %}
    <div class="mx-2 lg:mx-14 mt-10 border-2 border-[#C7EFE3] rounded-lg">
        <div class="mt-3 text-center text-2xl lg:text-4xl font-bold text-gray-50">Make an Appointment</div>

        <form class="p-8" method='post'>
        {% csrf_token %}
          <div class="flex gap-4">
            <input type="text" name='patient_name' class="mt-1 block w-1/2 rounded-md border border-slate-300 bg-white px-3 py-4 placeholder-slate-400 shadow-sm placeholder:font-semibold placeholder:text-gray-500 focus:border-sky-500 focus:outline-none focus:ring-1 focus:ring-sky-500 text-sm lg:text-md" value='{{patient.full_name}}' disabled />
            <input type="text" name="patient_phone" class="mt-1 block w-1/2 rounded-md border border-slate-300 bg-white px-3 py-4 placeholder-slate-400 shadow-sm placeholder:font-semibold placeholder:text-gray-500 focus:border-sky-500 focus:outline-none focus:ring-1 focus:ring-sky-500 text-sm lg:text-md" value='{{patient.phone_number}}' disabled />
          </div>
          <div class="my-6 flex gap-4">
            <select name="doctor" id="select" class="block w-1/2 rounded-md border border-slate-300 bg-white px-3 py-4 font-semibold text-gray-500 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-1 focus:ring-sky-500 text-sm lg:text-md">
                {% for doc in  doctors %}
                    <option class="font-semibold text-slate-300">{{doc.full_name}}</option>
                {% endfor %}
            </select>
            <select name="service" id="select" class="block w-1/2 rounded-md border border-slate-300 bg-white px-3 py-4 font-semibold text-gray-500 shadow-sm focus:border-sky-500 focus:outline-none focus:ring-1 focus:ring-sky-500 text-sm lg:text-md">
                {% for doc in  doctors %}
                    <option class="font-semibold text-slate-300">{{doc.service}}</option>
                {% endfor %}
            </select>
          </div>
          <div class="text-center py-6">
            {% if not patient_has %}
                <button type='submit' class="cursor-pointer rounded-lg bg-green-700/50 px-8 py-5 text-sm lg:text-md font-semibold text-white">Reserve</button>
            {% else %}
                <span class="rounded-lg text-blue-600/90 px-2 lg:px-8 py-5 text-lg font-bold underline">You Have an Appointment with Dr. {{reservation.doctor.full_name | upper}}</span>
                {% if pos %}
                    <div class='max-w-xs mx-auto mt-4 flex flex-col text-left gap-2 bg-blue-600/50 px-6 py-4 rounded-lg'>
                        <span class='text-white font-semibold'>Persons left:</span>
                        <span class='text-white font-bold'>{{infront}}</span>
                    </div>
                {% endif %}

            {% endif %}
          </div>
        </form>
      </div>
    {% endif %}
{% endblock content %}