account/urls.py
from django.urls import path
from .views import *

app_name= 'account'

urlpatterns = [
    path('', home, name='home'),
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='logout'),
    path('register/patient/', patient_register, name='patient_register'),
    path('register/doctor/', doctor_register, name='doctor_register'),
]

app/urls.py
from django.urls import path
from .views import home, call_patient

app_name = 'app'

urlpatterns = [
    path('', home, name='home'),
    path('call/<int:res_id>/', call_patient, name='call_patient'),
]

hospitalia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('account.urls')),
    path('', include('app.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="{% static "js/tailwindcss.js" %}"></script>

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body class='bg-[#1B2631]'>
    <!-- Main navigation container -->
    <nav class="relative flex w-full items-center justify-between bg-[#C7EFE3] py-2 shadow-dark-mild lg:py-4 px-2 lg:px-6">
    <div class='text-gray-800 font-semibold text-sm lg:text-lg px-2 pb-2 pt-2.5 uppercase'>
        <span class='text-gray-800 font-semibold text-sm lg:text-lg border-b-2 border-gray-800/80 px-2 pb-2 pt-2.5 uppercase'>
        Dashboard 
        </span>
      {% if request.user.is_doctor %}Dr.{{request.user}}{% endif %}
    </div>

      {% if not request.user.is_authenticated %}
          <div class="flex items-center">
            <a
              href='{% url "account:user_login" %}'
              data-twe-ripple-init
              data-twe-ripple-color="light"
              class="lg:me-3 inline-block rounded-lg px-2 pb-2 pt-2.5 bg-gray-800/80 text-[#C7EFE3] text-sm lg:text-lg font-semibold  hover:text-primary-600 focus:text-primary-600 focus:outline-none focus:ring-0 active:text-primary-700 ">
              Login
            </a>
            <a
              href='{% url "account:home" %}'
              data-twe-ripple-init
              data-twe-ripple-color="light"
              class="lg:me-3 inline-block border-b-2 border-gray-800 bg-primary mx-6 pb-2 pt-2.5 text-sm lg:text-lg font-semibold text-gray-800 shadow-primary-3 transition duration-150 ease-in-out hover:bg-primary-accent-300 hover:shadow-primary-2">
              Sign up
            </a>
          </div>
        {% else %}
          <a
            href='{% url "account:logout" %}'
            data-twe-ripple-init
            data-twe-ripple-color="light"
            class="lg:me-3 inline-block border-b-2 border-red-800 bg-primary mx-6 pb-2 pt-2.5 text-sm lg:text-lg font-semibold text-red-800 shadow-primary-3 transition duration-150 ease-in-out hover:bg-primary-accent-300 hover:shadow-primary-2">
            Logout
          </a>
        {% endif %}
    </nav>
    {% block content %} {% endblock content %}
  </body>
</html>